# Generated by Django 5.1.2 on 2024-11-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.URLField(max_length=500)),
                ('label', models.CharField(max_length=256)),
            ],
        ),
    ]
