# Generated by Django 5.1.2 on 2024-11-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='ac_type',
            new_name='kind',
        ),
    ]
