# Generated by Django 5.1.2 on 2024-11-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_image_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
            options={
                'unique_together': {('city', 'country', 'address', 'region')},
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='activities.location'),
        ),
    ]
